# Generated by Django 4.1.4 on 2023-09-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shares',
            new_name='Share',
        ),
    ]
