# Generated by Django 4.1.4 on 2023-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='blank-user-image.png', upload_to='user_image'),
        ),
    ]
