# Generated by Django 4.1.4 on 2023-10-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='State',
            field=models.CharField(default='state', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='LGA',
            field=models.CharField(default='LGA', max_length=100),
        ),
    ]
