# Generated by Django 4.1.4 on 2023-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
