# Generated by Django 4.1.4 on 2023-09-29 05:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.IntegerField()),
                ('expireDate', models.DateField()),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='dand',
            fields=[
                ('dandId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dandCounts', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dands', to='core.user')),
            ],
        ),
    ]
