# Generated by Django 4.1.4 on 2023-09-29 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loan_dand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('sharesId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sharesCounts', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('savingsId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savingsCounts', models.IntegerField()),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='core.user')),
            ],
        ),
    ]
