# Generated by Django 4.1.4 on 2023-09-30 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=50)),
                ('transactionCounts', models.IntegerField()),
                ('accountNo', models.IntegerField(default=123456789)),
                ('bank', models.TextField(default='Bank', max_length=100)),
                ('accountName', models.CharField(default='account name', max_length=100)),
            ],
        ),
    ]
