# Generated by Django 4.1.4 on 2023-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='BVN',
            field=models.CharField(default='BVN', max_length=100),
        ),
    ]
