# Generated by Django 4.1.4 on 2023-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='accountReference',
            field=models.CharField(default='123456fail', max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='accountStatus',
            field=models.CharField(default='notActive', max_length=100),
        ),
    ]
